inherit_from:
    - .rubocop_airbnb.yml

AllCops:
    Exclude:
        - 'app/views/users/notes/create.json.jbuilder'
        - 'db/**/*'
        - 'bin/*'
        - 'config/environments/*'
        - 'config/application.rb'
        - 'config/initializers/*'
        - 'config/spring.rb'
        - 'lib/tasks/*'
        - 'spec/*/*'
        - 'spec/spec_helper.rb'
        - 'spec/rails_helper.rb'
        - 'vendor/**/*'
        - 'path/ruby'
        - 'test/*/*/*'

LineLength:
  Max: 120
