version: '3'
services:
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: 13579515Ss
#       MYSQL_USER: root
#     volumes:
#       - mysql-data:/var/lib/mysql
#     ports:
#       - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/FashionInformation_app
      - public-data:/FashionInformation_app/public
      - tmp-data:/FashionInformation_app/tmp
      - log-data:/FashionInformation_app/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/FashionInformation_app/public
      - tmp-data:/FashionInformation_app/tmp
    ports:
      - fashioninformationsolution.net:80
    networks:
      default:
        aliases:
          - fashioninformationsolution.net

volumes:
  # mysql-data:
  public-data:
  tmp-data:
  log-data:
